### teste
GET  http://localhost:3000/
Content-Type: application/json
###

### Criar usuário
POST http://localhost:3000/auth/cadastro
Content-Type: application/json

{
  "nome": "joao",
  "senha": "1234"
}

###

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "nome": "joao",
  "senha": "123a4"
}

###

### Registrar peixe como visto
POST http://localhost:3000/peixe/viuPeixe
Content-Type: application/json

{
  "userID": 1,
  "peixeID": 5
}

###

### Registrar peixe como capturado
POST http://localhost:3000/peixe/pegouPeixe
Content-Type: application/json

{
  "userID": 1,
  "peixeID": 1,
  "tamanho": 23.5
}

###

### Consultar Peixedex do usuário
GET http://localhost:3000/peixe/peixedex/2

### registrar item enconrado
POST http://localhost:3000/item/adicionarIteminventario
Content-Type: application/json

{
  "userID": 1,
  "itemID": 1,
  "quantidade": 2
}

###

### Listar itens do usuário
GET http://localhost:3000/item/inventario/1

###